version: '3'
services:
  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    ports:
      - "3000:3000"
    volumes:
      - ./catalog-service/database.db:/usr/src/app/database.db
    networks:
      - bazar-network

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3001:3001"
    depends_on:
      - catalog-service
    volumes:
      - ./order-service/database.db:/usr/src/app/database.db
    networks:
      - bazar-network

  front-end-service:
    build: ./front-end-service
    container_name: front-end-service
    ports:
      - "3002:3002"
    depends_on:
      - catalog-service
      - order-service
    volumes:
      - ./middleware:/usr/src/app/middleware
    networks:
      - bazar-network

networks:
  bazar-network:
    driver: bridge