services:
  catalog-service-1:
    build: ./catalog-service
    container_name: catalog-service-1
    ports:
      - "3000:3000"
    volumes:
      - ./catalog-service/database.db:/usr/src/app/database.db
    networks:
      - bazar-network

  catalog-service-2:
    build: ./catalog-service
    container_name: catalog-service-2
    ports:
      - "3003:3000"
    volumes:
      - ./catalog-service/database.db:/usr/src/app/database.db
    networks:
      - bazar-network

  order-service-1:
    build: ./order-service
    container_name: order-service-1
    ports:
      - "3001:3001"
    depends_on:
      - catalog-service-1
    volumes:
      - ./order-service/database.db:/usr/src/app/database.db
    networks:
      - bazar-network

  order-service-2:
    build: ./order-service
    container_name: order-service-2
    ports:
      - "3004:3001"
    depends_on:
      - catalog-service-2
    volumes:
      - ./order-service/database.db:/usr/src/app/database.db
    networks:
      - bazar-network

  front-end-service:
    build: ./front-end-service
    container_name: front-end-service
    ports:
      - "3002:3002"
    depends_on:
      - catalog-service-1
      - order-service-1
      - catalog-service-2
      - order-service-2
    volumes:
      - ./middleware:/usr/src/app/middleware
    networks:
      - bazar-network

networks:
  bazar-network:
    driver: bridge
